### PR TITLE
update 1

### PR DESCRIPTION
**Pull request by jerabaul29**
Update 1, will need a bit of polishing.

### CODE REVIEW

**Comment by jerabaul29** [comment]
@joelvarunvasanth @franalcantara can you have a look and merge when it looks good to you? :)

**Comment by joelvarunvasanth** [comment]
Hi Jean, yes I have had a look at the pull request. I think it looks good. You have added the code from your repository, and have you made any changes to that code - such as the descriptive comments on each part of each script? Because the commits in the KTH repo do not show the diff of that. 

For the readme, i just have one suggestion - instead of saying the second type of installation (not recommended) is 'by hand', I guess you can say something like 'Manually install conda environment'? I just say this because 'by hand' seems a bit less specific. I know this is quite minor, but other than that, the entire thiing seems fine. If fran is ok ( I dont think he is part of this repo yet, as I cant tag him), then we are good to go.

**Comment by jerabaul29** [comment]
No changes to the code, I think it was fine / can be updated in further commits.

I can push an update to the title of the subsection tomorrow (I have to fix something else further tonight). Can you merge in the meantime, we can push a few updates over the next days :) .

**Comment by jerabaul29** [comment]
Sounds good!  @franalcantara can you confirm if this looks good to you? (of course this is just the first iteration, let us have further polishing happening through pull requests :) ).

**Comment by jerabaul29** [comment]
(would be great to merge this relatively soon, it will be much easier to apply "small polishing changes" once this is merged and we can focus on small individual changes :) ).

**Comment by franalcantara** [comment]
Yes, it looks good to me!

**Comment by jerabaul29** [comment]
Can you merge this @joelvarunvasanth ? And or maybe @franalcantara can do it? I cannot merge, as I do not have write access to this repo since I am not under the KTH organization.

**Comment by rvinuesa** [comment]
@jerabaul29 i sent you an invitation to the organization as “owner”, hopefully that makes the process easier for this and future repos 🙂

**Comment by jerabaul29** [comment]
Aaah, amazing, many thanks @rvinuesa :) . Indeed I can merge the pull request (and even push directly to this repo), this will make things much easier, many thanks :) . I had not thought about this possibility, I thought this was only possible for KTH employees, but I see this is not administered centrally by KTH ^^ :) .

**Comment by jerabaul29** [comment]
So this is merged, @franalcantara @joelvarunvasanth I can just push directly to this repo in the future, and no need for any of us to go through my fork any more :) .

**Comment by rvinuesa** [comment]
@jerabaul29 i wasn’t fully sure, but it seems it’s ok 🙂

**Pull request merged**
